serviceMaps:
  serviceName: birth-services
  mappings:
    - version: 1.0
        description: Persists birthCertificate details in eg_birth_dtls  table
        fromTopic: save-birth-details-topic
        isTransaction: true
        queryMaps:
          - query: INSERT INTO public.eg_birth_dtls (id, registrationno, hospitalname, dateofreport, dateofbirth, firstname, middlename, lastname, placeofbirth, informantsname, informantsaddress, createdtime, createdby, lastmodifiedtime, lastmodifiedby, counter, tenantid, gender, remarks, hospitalid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
            basePath: birthCertificate
            jsonMaps:
              - jsonPath: $.birthCertificate.id

              - jsonPath: $.birthCertificate.registrationno

              - jsonPath: $.birthCertificate.hospitalname

              - jsonPath: $.birthCertificate.dateofreport

              - jsonPath: $.birthCertificate.dateofbirth

              - jsonPath: $.birthCertificate.firstname

              - jsonPath: $.birthCertificate.middlename

              - jsonPath: $.birthCertificate.lastname

              - jsonPath: $.birthCertificate.placeofbirth

              - jsonPath: $.birthCertificate.informantsname

              - jsonPath: $.birthCertificate.informantsaddress

              - jsonPath: $.birthCertificate.createdtime

              - jsonPath: $.birthCertificate.createdby

              - jsonPath: $.birthCertificate.lastmodifiedtime

              - jsonPath: $.birthCertificate.lastmodifiedby

              - jsonPath: $.birthCertificate.counter

              - jsonPath: $.birthCertificate.tenantid

              - jsonPath: $.birthCertificate.gender

              - jsonPath: $.birthCertificate.remarks

              - jsonPath: $.birthCertificate.hospitalid

          - query: INSERT INTO public.eg_birth_father_info(id, firstname, middlename, lastname, aadharno, emailid, mobileno, education, proffession, nationality, religion, createdtime, createdby, lastmodifiedtime, lastmodifiedby, birthdtlid)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
            basePath: birthCertificate
            jsonMaps:
              - jsonPath: $.birthCertificate.id

              - jsonPath: $.birthCertificate.firstname

              - jsonPath: $.birthCertificate.middlename

              - jsonPath: $.birthCertificate.lastname

              - jsonPath: $.birthCertificate.aadharno

              - jsonPath: $.birthCertificate.emailid

              - jsonPath: $.birthCertificate.mobileno

              - jsonPath: $.birthCertificate.education

              - jsonPath: $.birthCertificate.proffession

              - jsonPath: $.birthCertificate.nationality

              - jsonPath: $.birthCertificate.religion

              - jsonPath: $.birthCertificate.createdtime

              - jsonPath: $.birthCertificate.createdby

              - jsonPath: $.birthCertificate.lastmodifiedtime

              - jsonPath: $.birthCertificate.lastmodifiedby

              - jsonPath: $.birthCertificate.birthdtlid

    - version: 1.0
      description: Persists birthCertificate details in eg_birth_cert_request  table
      fromTopic: save-birth-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO public.eg_birth_cert_request (id, birthcertificateno, createdby, createdtime, birthdtlid, filestoreid, lastmodifiedtime, lastmodifiedby, status, additionaldetail, embeddedurl, dateofissue, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: birthCertificate
          jsonMaps:
            - jsonPath: $.birthCertificate.id

            - jsonPath: $.birthCertificate.birthCertificateNo

            - jsonPath: $.birthCertificate.auditDetails.createdBy

            - jsonPath: $.birthCertificate.auditDetails.createdTime

            - jsonPath: $.birthCertificate.birthDtlId

            - jsonPath: $.birthCertificate.filestoreid

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.birthCertificate.applicationStatus

            - jsonPath: $.birthCertificate.additionalDetail
              type: JSON
              dbType: JSONB

            - jsonPath: $.birthCertificate.embeddedUrl

            - jsonPath: $.birthCertificate.dateofissue

            - jsonPath: $.birthCertificate.source

    - version: 1.0
      description: Update birthCertificate details in eg_birth_cert_request  table
      fromTopic: update-birth-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO eg_birth_cert_request_audit SELECT * FROM eg_birth_cert_request WHERE id = ?;
          basePath: birthCertificate
          jsonMaps:

            - jsonPath: $.birthCertificate.id

        - query: UPDATE eg_birth_cert_request SET status = ?, filestoreid =?, embeddedurl = ? ,dateofissue =?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
          basePath: birthCertificate
          jsonMaps:

            - jsonPath: $.birthCertificate.applicationStatus

            - jsonPath: $.birthCertificate.filestoreid

            - jsonPath: $.birthCertificate.embeddedUrl

            - jsonPath: $.birthCertificate.dateofissue

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.birthCertificate.id


    - version: 1.0
      description: Persists deathCertificate details in eg_death_cert_request  table
      fromTopic: save-death-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO public.eg_death_cert_request (id, deathcertificateno, createdby, createdtime, deathdtlid, filestoreid, lastmodifiedtime, lastmodifiedby, status, additionaldetail ,embeddedurl ,dateofissue, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: deathCertificate
          jsonMaps:
            - jsonPath: $.deathCertificate.id

            - jsonPath: $.deathCertificate.deathCertificateNo

            - jsonPath: $.deathCertificate.auditDetails.createdBy

            - jsonPath: $.deathCertificate.auditDetails.createdTime

            - jsonPath: $.deathCertificate.deathDtlId

            - jsonPath: $.deathCertificate.filestoreid

            - jsonPath: $.deathCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.deathCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.deathCertificate.applicationStatus

            - jsonPath: $.deathCertificate.additionalDetail
              type: JSON
              dbType: JSONB

            - jsonPath: $.deathCertificate.embeddedUrl

            - jsonPath: $.deathCertificate.dateofissue

            - jsonPath: $.deathCertificate.source

    - version: 1.0
      description: Update deathCertificate details in eg_death_cert_request  table
      fromTopic: update-death-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO eg_death_cert_request_audit SELECT * FROM eg_death_cert_request WHERE id = ?;
          basePath: deathCertificate
          jsonMaps:

            - jsonPath: $.deathCertificate.id

        - query: UPDATE eg_death_cert_request SET status = ?, filestoreid =?, embeddedurl = ? , dateofissue = ? , lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
          basePath: deathCertificate
          jsonMaps:

            - jsonPath: $.deathCertificate.applicationStatus

            - jsonPath: $.deathCertificate.filestoreid

            - jsonPath: $.deathCertificate.embeddedUrl

            - jsonPath: $.deathCertificate.dateofissue

            - jsonPath: $.deathCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.deathCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.deathCertificate.id
